// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaH9JBxb9EeS5NVabDBJzR4NW0t0pBO-M',
    appId: '1:45642392985:web:efa30c2880c5e8e01c9f08',
    messagingSenderId: '45642392985',
    projectId: 'netflix2-4f122',
    authDomain: 'netflix2-4f122.firebaseapp.com',
    storageBucket: 'netflix2-4f122.firebasestorage.app',
    measurementId: 'G-L7DMYY7XRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkE0veQms_e2tSjrdwI3NXGeyMkTJCEMA',
    appId: '1:45642392985:android:05c2d283a4c3e3591c9f08',
    messagingSenderId: '45642392985',
    projectId: 'netflix2-4f122',
    storageBucket: 'netflix2-4f122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6iT8Ne98T3SaxudopM2FXuJ1N7bQvyw',
    appId: '1:45642392985:ios:f789a9d45cab20d41c9f08',
    messagingSenderId: '45642392985',
    projectId: 'netflix2-4f122',
    storageBucket: 'netflix2-4f122.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg6iT8Ne98T3SaxudopM2FXuJ1N7bQvyw',
    appId: '1:45642392985:ios:f789a9d45cab20d41c9f08',
    messagingSenderId: '45642392985',
    projectId: 'netflix2-4f122',
    storageBucket: 'netflix2-4f122.firebasestorage.app',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaH9JBxb9EeS5NVabDBJzR4NW0t0pBO-M',
    appId: '1:45642392985:web:10b857016c8bb9c81c9f08',
    messagingSenderId: '45642392985',
    projectId: 'netflix2-4f122',
    authDomain: 'netflix2-4f122.firebaseapp.com',
    storageBucket: 'netflix2-4f122.firebasestorage.app',
    measurementId: 'G-KR6P3ZYNKT',
  );
}
